// Material Card Component

import { RedesignTheme } from "../redesign_palette.slint";

export component MaterialCard inherits Rectangle {
    in property <length> card-padding: RedesignTheme.t.s4;
    
    background: RedesignTheme.t.surface;
    border-radius: RedesignTheme.t.r-md;
    
    drop-shadow-color: #00000030;
    drop-shadow-blur: 4px;
    drop-shadow-offset-y: 2px;
    
    @children
}
