//! Sub-domain: turn.
//! Spec §2.1 — extracted from dialog_turn.rs (Round 6 refactor).
//! Contains private/pub(crate) helper methods; public API stays in the facade mod.rs.
//!
//! Sibling imports `use super::super::coordinator::*` for the struct definition.
//!
//! R34 refactor: persist methods moved to `turn_persist.rs`,
//! cancel/delete methods moved to `turn_cancel.rs`.

use super::super::coordinator::*;
use super::super::ports::*;
use super::super::scheduler::*;
use super::super::turn_outcome::TurnOutcome;

use crate::agentic::core::{MessageContent, SessionKind, SessionState};
use crate::agentic::events::EventQueue;
use crate::agentic::session::SessionManager;
use crate::util::errors::NortHingResult;
use std::sync::atomic::Ordering;
use std::sync::Arc;
use tokio::time::{sleep, Duration, Instant};
use tracing::{debug, info, warn};

const MANUAL_COMPACTION_COMMAND: &str = "/compact";
const CONTEXT_COMPRESSION_TOOL_NAME: &str = "ContextCompression";
const DEFAULT_SUBAGENT_MAX_CONCURRENCY: usize = 5;
const MAX_SUBAGENT_MAX_CONCURRENCY: usize = 64;

impl ConversationCoordinator {
    pub(super) fn ensure_user_message_metadata_object(metadata: Option<serde_json::Value>) -> serde_json::Value {
        match metadata {
            Some(value) if value.is_object() => value,
            Some(value) => serde_json::json!({ "raw_metadata": value }),
            None => serde_json::json!({}),
        }
    }

    pub(super) fn assistant_bootstrap_kickoff_query(is_chinese: bool) -> &'static str {
        if is_chinese {
            "请开始初始化"
        } else {
            "Please start bootstrap"
        }
    }

    pub(super) async fn is_chinese_locale() -> bool {
        use crate::service::config::get_global_config_service;
        use crate::service::config::types::AppConfig;
        let Ok(config_service) = get_global_config_service().await else {
            return false;
        };
        let app: AppConfig = config_service.config(Some("app")).await.unwrap_or_default();
        app.language.starts_with("zh")
    }

    pub(super) fn assistant_bootstrap_system_reminder(kickoff_query: &str, expected_reply_language: &str) -> String {
        format!(
            "This is an automatic bootstrap kickoff generated by the system because this assistant workspace still contains BOOTSTRAP.md. \
Treat the user message `{kickoff_query}` only as a start signal, begin bootstrap immediately, and finish it in this session. \
Use {expected_reply_language} for all user-facing replies during bootstrap unless the user later asks to switch languages. \
Update the persona files and delete BOOTSTRAP.md as soon as bootstrap is complete."
        )
    }

    pub(super) async fn finalize_turn_in_workspace(
        session_id: &str,
        turn_id: &str,
        turn_index: usize,
        agent_type: &str,
        user_input: &str,
        workspace_path: &str,
        // Pre-resolved on-disk session storage path (mirror dir for remote workspaces).
        // When present we use it directly so we never re-resolve without remote SSH info
        // (which would slugify a raw remote POSIX path under `~/.northhing/projects/`).
        resolved_session_storage_path: Option<&std::path::Path>,
        status: crate::service::session::TurnStatus,
        user_message_metadata: Option<serde_json::Value>,
    ) {
        use crate::agentic::persistence::PersistenceManager;
        use crate::infrastructure::PathManager;
        use crate::service::session::{DialogTurnData, SessionMetadata, SessionStatus, UserMessageData};

        let path_manager = match PathManager::new() {
            Ok(pm) => std::sync::Arc::new(pm),
            Err(_) => return,
        };

        let workspace_path_buf = match resolved_session_storage_path {
            Some(p) => p.to_path_buf(),
            None => std::path::PathBuf::from(workspace_path),
        };
        let persistence_manager = match PersistenceManager::new(path_manager) {
            Ok(manager) => manager,
            Err(_) => return,
        };

        if let Ok(Some(_existing)) = persistence_manager
            .load_dialog_turn(&workspace_path_buf, session_id, turn_index)
            .await
        {
            return;
        }

        let now_ms = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64;

        if let Ok(None) = persistence_manager
            .load_session_metadata(&workspace_path_buf, session_id)
            .await
        {
            let metadata = SessionMetadata {
                session_id: session_id.to_string(),
                session_name: "Recovered Session".to_string(),
                agent_type: "agentic".to_string(),
                last_user_dialog_agent_type: None,
                last_submitted_agent_type: None,
                created_by: None,
                session_kind: SessionKind::Standard,
                model_name: "default".to_string(),
                created_at: now_ms,
                last_active_at: now_ms,
                turn_count: 0,
                message_count: 0,
                tool_call_count: 0,
                status: SessionStatus::Active,
                terminal_session_id: None,
                snapshot_session_id: None,
                tags: Vec::new(),
                custom_metadata: None,
                relationship: None,
                todos: None,
                deep_review_run_manifest: None,
                deep_review_cache: None,
                workspace_path: Some(workspace_path.to_string()),
                workspace_hostname: None,
                unread_completion: None,
                needs_user_attention: None,
            };
            if let Err(e) = persistence_manager
                .save_session_metadata(&workspace_path_buf, &metadata)
                .await
            {
                warn!(
                    "Failed to create fallback session metadata during turn finalization: session_id={}, error={}",
                    session_id, e
                );
                // Do not return: on read-only or transient IO errors we still try to persist the
                // minimal dialog turn so local/remote UI history is not silently empty.
            }
        }

        let mut turn_data = DialogTurnData::new(
            turn_id.to_string(),
            turn_index,
            session_id.to_string(),
            UserMessageData {
                id: format!("{}-user", turn_id),
                content: user_input.to_string(),
                timestamp: now_ms,
                metadata: user_message_metadata,
            },
        );
        turn_data.agent_type = Some(agent_type.to_string());
        turn_data.status = status;
        turn_data.end_time = Some(now_ms);
        turn_data.duration_ms = Some(now_ms.saturating_sub(turn_data.start_time));

        if let Err(e) = persistence_manager
            .save_dialog_turn(&workspace_path_buf, &turn_data)
            .await
        {
            warn!(
                "Failed to finalize turn in workspace: session_id={}, turn_index={}, error={}",
                session_id, turn_index, e
            );
        }
    }

    /// P0-8: Wait until all in-flight spawn tasks for this session have
    /// drained, or until `deadline` is reached. Returns the number of
    /// in-flight turns still running (0 means fully drained). This is used to
    /// serialize cancel→start so a new turn does not start mutating the
    /// in-memory context cache while a cancelled turn's spawn task is still
    /// finishing its tail.

    pub(super) async fn wait_session_drained(&self, session_id: &str, max_wait: Duration) -> usize {
        let counter = match self.active_turns_per_session.get(session_id) {
            Some(entry) => entry.value().clone(),
            None => return 0,
        };
        let deadline = Instant::now() + max_wait;
        loop {
            let pending = counter.load(Ordering::SeqCst);
            if pending == 0 {
                return 0;
            }
            if Instant::now() >= deadline {
                return pending;
            }
            sleep(Duration::from_millis(20)).await;
        }
    }
}
