//! Execution Engine Type Definitions

use crate::agentic::core::Message;
use crate::agentic::round_preempt::{DialogRoundInjectionInterrupt, DialogRoundInjectionSource};
use crate::agentic::tools::pipeline::SubagentParentInfo;
use crate::agentic::tools::ToolRuntimeRestrictions;
use crate::agentic::workspace::WorkspaceServices;
use crate::agentic::WorkspaceBinding;
pub use northhing_agent_runtime::events::FinishReason;
use northhing_core_types::ai::ToolDefinition;
use northhing_runtime_ports::DelegationPolicy;
use serde_json::Value;
use std::collections::HashMap;
use std::sync::Arc;
use tokio_util::sync::CancellationToken;

/// Execution context
#[derive(Clone)]
pub struct ExecutionContext {
    pub session_id: String,
    pub dialog_turn_id: String,
    pub turn_index: usize,
    pub agent_type: String,
    pub workspace: Option<WorkspaceBinding>,
    pub context: HashMap<String, String>,
    pub subagent_parent_info: Option<SubagentParentInfo>,
    pub(crate) delegation_policy: DelegationPolicy,
    pub skip_tool_confirmation: bool,
    pub runtime_tool_restrictions: ToolRuntimeRestrictions,
    /// Workspace I/O services (filesystem + shell) injected into tools
    pub workspace_services: Option<WorkspaceServices>,
    /// When set, engine drains pending round injections at each round boundary
    /// and injects them into the dialog history without ending the turn.
    pub round_injection: Option<Arc<dyn DialogRoundInjectionSource>>,
    /// When true, stream cancellation may be converted into a partial assistant
    /// result if text/tool output has already been produced.
    pub recover_partial_on_cancel: bool,
}

/// Round context
#[derive(Debug, Clone)]
pub struct RoundContext {
    pub session_id: String,
    pub subagent_parent_info: Option<SubagentParentInfo>,
    pub dialog_turn_id: String,
    pub turn_index: usize,
    pub round_number: usize,
    pub workspace: Option<WorkspaceBinding>,
    pub messages: Vec<Message>,
    pub available_tools: Vec<String>,
    pub collapsed_tools: Vec<String>,
    pub unlocked_collapsed_tools: Vec<String>,
    pub model_name: String,
    pub agent_type: String,
    pub context_vars: HashMap<String, String>,
    pub(crate) delegation_policy: DelegationPolicy,
    pub runtime_tool_restrictions: ToolRuntimeRestrictions,
    /// Cooperative interrupt checked by tool execution so round injections can be
    /// applied after the currently running atomic tool/batch finishes.
    pub steering_interrupt: Option<DialogRoundInjectionInterrupt>,
    pub cancellation_token: CancellationToken,
    pub workspace_services: Option<WorkspaceServices>,
    pub recover_partial_on_cancel: bool,
}

/// Round result
#[derive(Debug, Clone)]
pub struct RoundResult {
    pub assistant_message: Message,
    pub tool_calls: Vec<crate::agentic::core::ToolCall>,
    pub tool_result_messages: Vec<Message>,
    pub has_more_rounds: bool,
    pub finish_reason: FinishReason,
    /// Token usage statistics (from model response)
    pub usage: Option<crate::util::types::ai::GeminiUsage>,
    /// Provider-specific metadata returned by the model.
    pub provider_metadata: Option<Value>,
    /// When set, this round's stream was partially recovered (aborted mid-way
    /// but some output was already received). Contains a human-readable reason.
    pub partial_recovery_reason: Option<String>,
    /// True when the model emitted any non-empty assistant text in this round.
    /// Used by the execution engine to distinguish "model gave a final answer"
    /// (text-only round, end the turn) from "model stalled with thinking-only"
    /// (no text, no tool_call — needs rescue).
    pub had_assistant_text: bool,
    /// True when the model emitted any non-empty thinking / reasoning content
    /// in this round.
    pub had_thinking_content: bool,
}

/// Execution result
#[derive(Debug, Clone)]
pub struct ExecutionResult {
    /// Last assistant message
    pub final_message: Message,
    pub total_rounds: usize,
    /// Number of tool invocations across all rounds of this turn
    /// (mirrors `ExecutionTurnState::total_tools` at completion time).
    pub total_tools: usize,
    /// Wall-clock duration of the turn in milliseconds.
    pub duration_ms: u64,
    pub success: bool,
    /// All new messages generated by this execution (including AI responses and tool results)
    pub new_messages: Vec<Message>,
    /// Why the execution finished
    pub finish_reason: FinishReason,
    /// When set, the turn finished but the last model round was a partial
    /// recovery (stream aborted mid-way). Mirrors
    /// `ExecutionTurnState::last_partial_recovery_reason` at completion time.
    pub partial_recovery_reason: Option<String>,
}

/// Result of one `ExecutionEngine::tick` call.
#[derive(Debug, Clone)]
pub enum RoundTickResult {
    /// Drive another round. The caller should call `tick` again
    /// with the updated state.
    Continue,
    /// The turn is complete. Finalize (if needed) and return.
    Done,
    /// The turn was cancelled.
    Cancelled,
    /// An error occurred.
    Error { error: String },
}

/// Mutable state for a single dialog turn, extracted from
/// `execute_dialog_turn_impl`'s local variables so it can persist
/// across `tick` calls.
///
/// This is the A2 refactoring: the monolithic loop's mutable state
/// becomes a struct that can be passed between `init_turn`, `tick`,
/// and `finalize_turn` calls.
#[derive(Debug, Clone)]
pub struct ExecutionTurnState {
    // Messages (primary mutable state)
    pub messages: Vec<Message>,
    pub system_prompt_message: Message,

    // Round counters
    pub round_index: usize,
    pub completed_rounds: usize,
    pub total_tools: usize,

    // Loop detection
    pub recent_tool_signatures: Vec<String>,
    pub recent_failed_tool_signatures: Vec<String>,
    pub failed_tool_recovery_attempts: usize,
    pub partial_continuation_attempts: usize,
    pub thinking_only_rescue_attempts: usize,

    // Compression health
    pub full_compression_count: usize,
    pub compression_failure_count: u32,
    pub consecutive_compression_failures: u32,

    // Token tracking
    pub last_usage: Option<crate::util::types::ai::GeminiUsage>,
    pub last_partial_recovery_reason: Option<String>,

    // Finalization
    pub finalization_reason: Option<&'static str>,

    // Context variables (injected into each round)
    pub execution_context_vars: HashMap<String, String>,

    // Cached immutable data (set once during init)
    pub session_id: String,
    pub dialog_turn_id: String,
    pub workspace: Option<WorkspaceBinding>,
    pub ai_client: std::sync::Arc<crate::infrastructure::ai::AIClient>,
    pub agent_type: String,
    pub model_id: String,
    pub resolved_primary_model_id: String,
    pub primary_supports_image_understanding: bool,
    pub context_window: usize,
    pub available_tools: Vec<String>,
    pub collapsed_tools: Vec<String>,
    pub tool_definitions: Option<Vec<ToolDefinition>>,
    pub prepended_reminders: northhing_agent_runtime::prompt::PrependedPromptReminders,
    pub context_profile_policy: crate::agentic::context_profile::ContextProfilePolicy,
    pub enable_context_compression: bool,
    pub compression_threshold: f32,
}

impl ExecutionTurnState {
    /// Construct from `ExecutionTurnSetup` — all mutable counters start at zero.
    pub fn from_setup(setup: ExecutionTurnSetup) -> Self {
        let mut messages = vec![setup.system_prompt_message.clone()];
        messages.extend(setup.initial_messages);
        Self {
            messages,
            system_prompt_message: setup.system_prompt_message,
            round_index: 0,
            completed_rounds: 0,
            total_tools: 0,
            recent_tool_signatures: Vec::new(),
            recent_failed_tool_signatures: Vec::new(),
            failed_tool_recovery_attempts: 0,
            partial_continuation_attempts: 0,
            thinking_only_rescue_attempts: 0,
            full_compression_count: 0,
            compression_failure_count: 0,
            consecutive_compression_failures: 0,
            last_usage: None,
            last_partial_recovery_reason: None,
            finalization_reason: None,
            execution_context_vars: setup.execution_context_vars,
            session_id: setup.session_id,
            dialog_turn_id: setup.dialog_turn_id,
            workspace: setup.workspace,
            ai_client: setup.ai_client,
            agent_type: setup.agent_type,
            model_id: setup.model_id,
            resolved_primary_model_id: setup.resolved_primary_model_id,
            primary_supports_image_understanding: setup.primary_supports_image_understanding,
            context_window: setup.context_window,
            available_tools: setup.available_tools,
            collapsed_tools: setup.collapsed_tools,
            tool_definitions: setup.tool_definitions,
            prepended_reminders: setup.prepended_reminders,
            context_profile_policy: setup.context_profile_policy,
            enable_context_compression: setup.enable_context_compression,
            compression_threshold: setup.compression_threshold,
        }
    }
}

/// Builder for `ExecutionTurnState` — collects all the immutable
/// setup data so `init_turn` can construct the state in one place.
pub struct ExecutionTurnSetup {
    pub session_id: String,
    pub dialog_turn_id: String,
    pub workspace: Option<WorkspaceBinding>,
    pub ai_client: Arc<crate::infrastructure::ai::AIClient>,
    pub agent_type: String,
    pub model_id: String,
    pub resolved_primary_model_id: String,
    pub primary_supports_image_understanding: bool,
    pub context_window: usize,
    pub available_tools: Vec<String>,
    pub collapsed_tools: Vec<String>,
    pub tool_definitions: Option<Vec<ToolDefinition>>,
    pub prepended_reminders: northhing_agent_runtime::prompt::PrependedPromptReminders,
    pub context_profile_policy: crate::agentic::context_profile::ContextProfilePolicy,
    pub enable_context_compression: bool,
    pub compression_threshold: f32,
    pub system_prompt_message: Message,
    pub initial_messages: Vec<Message>,
    pub execution_context_vars: HashMap<String, String>,
}
